sudo: required

language: node_js
node_js:
  - "5.11"

services:
  - docker

before_install:
  - rvm install 2.1
  - gem install bundler
  - bundle install
  - mkdir $PWD/travis-phantomjs
  - curl -sSL https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 -o $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - curl -sSL http://deis.io/deis-cli/install-v2.sh | bash
  - sudo ln -fs $PWD/deis /usr/local/bin/deis
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH

before_script:
 - npm install -g gulp grunt

script:
  - make build build-image

deploy:
  - provider: script
    script: make push deploy

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  directories:
    - node_modules
