# Site settings
title: "Coming Soon: Helm"
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Helm: The Kubernetes Package Manager
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://helm.sh" # the base hostname & protocol for your site
twitter_username: opendeis
github_username:  deis

# Build settings
markdown: kramdown
