baseurl = "https://v3.helm.sh/"
languageCode = "en-us"
title = "Helm"
theme = "helm"

contentDir = "content"
publishdir = "app"

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[params]
  title = "Helm"
  author = "Ronan Flynn-Curran"
  description = "Helm - The Kubernetes Package Manager."
  googleAnalyticsId = "UA-42867143-2"
  googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
  jsFiles = [
    "foundation",
    "foundation.accordion",
    "foundation.dropdown",
    "foundation.offcanvas",
    "foundation.slider",
    "foundation.tooltip",
    "modernizr",
    "app"
  ]

[Permalinks]
  code = "/:filename/"

[[menu.docs]]
  name = "Docs Home"
  identifier = "home"
  url = "/docs"
  weight = 1
[[menu.docs]]
  name = "Introduction"
  identifier = "intro"
  url = "/docs/intro"
  weight = 2
[[menu.docs]]
  name = "How-to"
  identifier = "howto"
  url = "/docs/howto"
  weight = 3
[[menu.docs]]
  name = "Topics"
  identifier = "topics"
  url = "/docs/topics"
  weight = 4
[[menu.docs]]
  name = "Best Practices"
  identifier = "chart_best_practices"
  url = "/docs/topics/chart_best_practices"
  weight = 5
[[menu.docs]]
  name = "Developing Templates"
  identifier = "chart_template_guide"
  url = "/docs/topics/chart_template_guide"
  weight = 6
[[menu.docs]]
  name = "Community"
  identifier = "community"
  url = "/docs/community"
  weight = 7
