baseurl = "https://v3.helm.sh/"
languageCode = "en-us"
title = "Helm"
theme = "helm"

contentDir = "content"
publishdir = "app"

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  title = "Helm"
  author = "Ronan Flynn-Curran"
  description = "Helm - The Kubernetes Package Manager."
  googleAnalyticsId = "UA-42867143-2"
  googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
  jsFiles = [
    "foundation",
    "foundation.accordion",
    "foundation.dropdown",
    "foundation.offcanvas",
    "foundation.slider",
    "foundation.tooltip",
    "modernizr",
    "app"
  ]

[[params.versions]]
version = "v3.0.0"
patch = "beta.1"
url = "https://v3.helm.sh/docs"
primary = true

[[params.versions]]
version = "v2.14.3"
patch = "stable"
url = "https://helm.sh/docs"

[[params.versions]]
version = "v2.14.0"
url = "https://v2-14-0.helm.sh/docs"

[Permalinks]
  code = "/:filename/"

[[params.quicklinks]]
title = "Quickstart Guide"
description = "How to install and get started with Helm including instructions for distros, FAQs, and plugins."
url = "/docs/intro/quickstart"

[[params.quicklinks]]
title = "Chart Guide"
description = "Practical steps for building Helm charts—how to structure, sign, and sync your charts."
url = "/docs/topics/charts"

[[params.quicklinks]]
title = "Deploying to Kubernetes"
description = "Helm can deploy apps to Kubernetes, with release and rollback versioning"
url = "https://daemonza.github.io/2017/02/20/using-helm-to-deploy-to-kubernetes"
via = "daemonza"

[[params.quicklinks]]
title = "CI/CD for Kubernetes"
description = "Instructions on using Helm as the missing CI/CD Kubernetes component"
url = "https://daemonza.github.io/2017/02/20/using-helm-to-deploy-to-kubernetes"
via = "hackernoon"
