[build]
  base    = ""
  command = "gulp && hugo"
  publish = "app"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# A basic redirect rule
[[redirects]]
  from = "https://docs.helm.sh/*"
  to = "https://helm.sh/docs/:splat"