[build]
  command = "gulp && hugo --minify"
  publish = "app"

[build.environment]
  HUGO_VERSION = "0.55.6"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# redirect docs homepage
[[redirects]]
  from = "https://docs.helm.sh/"
  to = "https://helm.sh/docs/"

# redirect docs subpages 
[[redirects]]
  from = "https://docs.helm.sh/*"
  to = "https://helm.sh/docs/:splat"

[[redirects]] # from v3 to latest
  from = "/blog/"
  to = "https://helm.sh/blog"
  status = 301
  force = true

[[redirects]] # from v3 to latest
  from = "/blog/*"
  to = "https://helm.sh/blog/:splat"
  status = 301
  force = true

[[redirects]] # from v3 to latest
  from = "https://v2-helm.netlify.com/blog/"
  to = "https://helm.sh/blog"
  status = 301
  force = true

[[redirects]] # from v3 to latest
  from = "https://v2-helm.netlify.com/blog/*"
  to = "https://helm.sh/blog/:splat"
  status = 301
  force = true

[[redirects]] # from v3 to latest
  from = "https://v2.helm.sh/blog/"
  to = "https://helm.sh/blog"
  status = 301
  force = true

[[redirects]] # from v3 to latest
  from = "https://v2.helm.sh/blog/*"
  to = "https://helm.sh/blog/:splat"
  status = 301
  force = true