baseurl = "https://docs.helm.sh/"
languageCode = "en-us"
title = "Helm Docs"
theme = "helmdocs"

contentDir = "source/docs"
publishdir = "app"

[params]
    title = "Helm Docs"
    author = "Ronan Flynn-Curran"
    description = "Documentation for Helm - The Kubernetes Package Manager."

canonifyURLs = "false"
relativeURLs = "true"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"

[[menu.main]]
  name = "Using Helm"
  url = "/using_helm/#"
  identifier = "using_helm"
  weight = 1
  [[menu.main]]
    name = "Quickstart"
    url = "/quickstart/#"
    identifier = "quickstart"
    weight = 21
    parent = "using_helm"
  [[menu.main]]
    name = "Installing Helm"
    url = "/install/#"
    identifier = "install"
    weight = 22
    parent = "using_helm"
  [[menu.main]]
    name = "Kubernetes Distro Notes"
    url = "/kubernetes_distros/#"
    identifier = "kubernetes_distros"
    weight = 23
    parent = "using_helm"
  [[menu.main]]
    name = "Install FAQ"
    url = "/install_faq/#"
    identifier = "install_faq"
    weight = 24
    parent = "using_helm"
  [[menu.main]]
    name = "Using Helm"
    url = "/using_helm/#"
    identifier = "usinghelm"
    weight = 25
    parent = "using_helm"
  [[menu.main]]
    name = "Plugins"
    url = "/plugins/#"
    identifier = "plugins"
    weight = 26
    parent = "using_helm"

[[menu.main]]
    name = "Helm Commands"
    url = "/helm/"
    identifier = "helm"
    weight = 2
    [[menu.main]]
      name = "Helm"
      url = "helm"
      identifier = "helm-command"
      weight = 21
      parent = "helm"
    [[menu.main]]
      name = "Helm Completion"
      url = "helm-completion"
      identifier = "helm-completion"
      weight = 22
      parent = "helm"
    [[menu.main]]
      name = "Helm Create"
      url = "helm-create"
      identifier = "helm-create"
      weight = 23
      parent = "helm"
    [[menu.main]]
      name = "Helm Delete"
      url = "helm-delete"
      identifier = "helm-delete"
      weight = 24
      parent = "helm"
    [[menu.main]]
      name = "Helm Dependency"
      url = "helm-dependency"
      identifier = "helm-dependency"
      weight = 25
      parent = "helm"
    [[menu.main]]
      name = "Helm Dependency Build"
      url = "helm-dependency-build"
      identifier = "helm-dependency-build"
      weight = 26
      parent = "helm"
    [[menu.main]]
      name = "Helm Dependency List"
      url = "helm-dependency-list"
      identifier = "helm-dependency-list"
      weight = 27
      parent = "helm"
    [[menu.main]]
      name = "Helm Dependency Update"
      url = "helm-dependency-update"
      identifier = "helm-dependency-update"
      weight = 28
      parent = "helm"
    [[menu.main]]
      name = "Helm Fetch"
      url = "helm-dependency-update"
      identifier = "helm-dependency-update"
      weight = 29
      parent = "helm"
    [[menu.main]]
      name = "Helm Get"
      url = "helm-get"
      identifier = "helm-get"
      weight = 30
      parent = "helm"
    [[menu.main]]
      name = "Helm Get Hooks"
      url = "helm-get-hooks"
      identifier = "helm-get-hooks"
      weight = 31
      parent = "helm"
    [[menu.main]]
      name = "Helm Get Manifest"
      url = "helm-get-manifest"
      identifier = "helm-get-manifest"
      weight = 32
      parent = "helm"
    [[menu.main]]
      name = "Helm Get Values"
      url = "helm-get-values"
      identifier = "helm-get-values"
      weight = 33
      parent = "helm"
    [[menu.main]]
      name = "Helm History"
      url = "helm-history"
      identifier = "helm-history"
      weight = 34
      parent = "helm"
    [[menu.main]]
      name = "Helm Home"
      url = "helm-home"
      identifier = "helm-home"
      weight = 35
      parent = "helm"
    [[menu.main]]
      name = "Helm Init"
      url = "helm-init"
      identifier = "helm-init"
      weight = 36
      parent = "helm"
    [[menu.main]]
      name = "Helm Inspect"
      url = "helm-inspect"
      identifier = "helm-inspect"
      weight = 37
      parent = "helm"
    [[menu.main]]
      name = "Helm Inspect Chart"
      url = "helm-inspect-chart"
      identifier = "helm-inspect-chart"
      weight = 38
      parent = "helm"
    [[menu.main]]
      name = "Helm Inspect Values"
      url = "helm-inspect-values"
      identifier = "helm-inspect-values"
      weight = 39
      parent = "helm"
    [[menu.main]]
      name = "Helm Install"
      url = "helm-install"
      identifier = "helm-install"
      weight = 40
      parent = "helm"
    [[menu.main]]
      name = "Helm Lint"
      url = "helm-lint"
      identifier = "helm-lint"
      weight = 41
      parent = "helm"
    [[menu.main]]
      name = "Helm List"
      url = "helm-list"
      identifier = "helm-list"
      weight = 42
      parent = "helm"
    [[menu.main]]
      name = "Helm Package"
      url = "helm-package"
      identifier = "helm-package"
      weight = 43
      parent = "helm"
    [[menu.main]]
      name = "Helm Plugin"
      url = "helm-plugin"
      identifier = "helm-plugin"
      weight = 44
      parent = "helm"
    [[menu.main]]
      name = "Helm Plugin Install"
      url = "helm-plugin-install"
      identifier = "helm-plugin-install"
      weight = 45
      parent = "helm"
    [[menu.main]]
      name = "Helm Plugin List"
      url = "helm-plugin-list"
      identifier = "helm-plugin-list"
      weight = 46
      parent = "helm"
    [[menu.main]]
      name = "Helm Plugin Remove"
      url = "helm-plugin-remove"
      identifier = "helm-plugin-remove"
      weight = 47
      parent = "helm"
    [[menu.main]]
      name = "Helm Plugin Update"
      url = "helm-plugin-update"
      identifier = "helm-plugin-update"
      weight = 48
      parent = "helm"
    [[menu.main]]
      name = "Helm Repo"
      url = "helm-repo"
      identifier = "helm-repo"
      weight = 49
      parent = "helm"
    [[menu.main]]
      name = "Helm Repo Add"
      url = "helm-repo-add"
      identifier = "helm-repo-add"
      weight = 50
      parent = "helm"
    [[menu.main]]
      name = "Helm Repo Index"
      url = "helm-repo-index"
      identifier = "helm-repo-index"
      weight = 51
      parent = "helm"
    [[menu.main]]
      name = "Helm Repo List"
      url = "helm-rep-listo"
      identifier = "helm-repo-list"
      weight = 52
      parent = "helm"
    [[menu.main]]
      name = "Helm Repo Remove"
      url = "helm-repo-remove"
      identifier = "helm-repo-remove"
      weight = 53
      parent = "helm"
    [[menu.main]]
      name = "Helm Repo Update"
      url = "helm-repo-update"
      identifier = "helm-repo-update"
      weight = 54
      parent = "helm"
    [[menu.main]]
      name = "Helm Reset"
      url = "helm-reset"
      identifier = "helm-reset"
      weight = 55
      parent = "helm"
    [[menu.main]]
      name = "Helm Rollback"
      url = "helm-rollback"
      identifier = "helm-rollback"
      weight = 56
      parent = "helm"
    [[menu.main]]
      name = "Helm Search"
      url = "helm-search"
      identifier = "helm-search"
      weight = 57
      parent = "helm"
    [[menu.main]]
      name = "Helm Serve"
      url = "helm-serve"
      identifier = "helm-serve"
      weight = 58
      parent = "helm"
    [[menu.main]]
      name = "Helm Status"
      url = "helm-status"
      identifier = "helm-status"
      weight = 59
      parent = "helm"
    [[menu.main]]
      name = "Helm Test"
      url = "helm-test"
      identifier = "helm-test"
      weight = 60
      parent = "helm"
    [[menu.main]]
      name = "Helm Upgrade"
      url = "helm-upgrade"
      identifier = "helm-upgrade"
      weight = 61
      parent = "helm"
    [[menu.main]]
      name = "Helm Verify"
      url = "helm-verify"
      identifier = "helm-verify"
      weight = 62
      parent = "helm"
    [[menu.main]]
      name = "Helm Version"
      url = "helm-version"
      identifier = "helm-version"
      weight = 63
      parent = "helm"

[[menu.main]]
    name = "Charts"
    url = "/charts/#"
    identifier = "developing-charts"
    weight = 3
[[menu.main]]
    name = "Developing Templates"
    url = "/chart_template_guide/#"
    identifier = "chart_template_guide"
    weight = 4
[[menu.main]]
    name = "Best Practices"
    url = "/chart_best_practices/#"
    identifier = "chart_best_practices"
    weight = 5
[[menu.main]]
    name = "Related Projects"
    url = "/related/#"
    identifier = "related-projects"
    weight = 6
[[menu.main]]
    name = "Architecture"
    url = "/architecture/#"
    identifier = "architecture"
    weight = 7
[[menu.main]]
    name = "Developer Guide"
    url = "/developers/#"
    identifier = "developer-guide"
    weight = 8
[[menu.main]]
    name = "History"
    url = "/history/#"
    identifier = "history"
    weight = 9
[[menu.main]]
    name = "Glossary"
    url = "/glossary/#"
    identifier = "glossary"
    weight = 10
[[menu.main]]
    name = "Find Charts"
    url = "https://kubeapps.com/"
    weight = 11
